[참고 도서: 딥러닝 파이토치 교과서](https://www.yes24.com/Product/Goods/107664335)

# 2.1 파이토치 개요
## 2.1.1 파이토치 특징 및 장점

In [3]:
import torch

In [4]:
torch.tensor([[1, -1], [1, -1]])

tensor([[ 1, -1],
        [ 1, -1]])

# 2.2 파이토치 기초 문법
## 2.2.1 텐서 다루기

텐서는 넘파이의 ndarray와 비슷하고 GPU에서 연산도 가능하다

In [7]:
# 텐서 생성, GPU에 텐서 생성, dtype 이용해 텐서 생성
# colab에서 GPU를 사용할 경우, 별도로 노트 설정 옵션을 조정해야 함
print(torch.tensor([[1, 2], [3, 4]]))
# print(torch.tensor([[1, 2], [3, 4]], device = "cuda:0"))
print(torch.tensor([[1, 2], [3, 4]], dtype = torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


인덱스를 바로 지정하거나 슬라이스를 사용할 수 있다

In [8]:
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy())

[[1 2]
 [3 4]]


In [9]:
temp = torch.tensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print(temp[2:5], temp[4:-1])

tensor(1) tensor(2) tensor(7)
tensor([3, 4, 5]) tensor([5, 6])


텐서 간 타입이 다르면 연산이 불가능하다.  
- torch.FloatTensor: 32비트의 부동 소수점
- torch.DoubleTensor: 64비트의 부동 소수점
- torch.LongTensor: 4비트의 부호가 있는 정수

차원을 변경하는 방법: view, reshape과 유사함  
텐서를 결합하는 방법: stack, cat  
차원을 교환하는 방법: t, transpose

In [34]:
temp = torch.tensor([
    [1, 2], [3, 4]
])
print('텐서의 크기')
print(temp.shape)
print('\n텐서를 4*1로 변경')
print(temp.view(4,1))
print('\n텐서를 1차원 벡터로 변경')
print(temp.view(-1))
print('\n텐서를 1*?로 변경')
print(temp.view(1, -1))
print('\n텐서를 ?*1로 변경')
print(temp.view(-1, 1))
print('\n텐서를 4*?로 변경')
print(temp.view(4, -1))
print('\n텐서를 ?*4로 변경')
print(temp.view(-1, 4))

텐서의 크기
torch.Size([2, 2])

텐서를 4*1로 변경
tensor([[1],
        [2],
        [3],
        [4]])

텐서를 1차원 벡터로 변경
tensor([1, 2, 3, 4])

텐서를 1*?로 변경
tensor([[1, 2, 3, 4]])

텐서를 ?*1로 변경
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3, 4]])


In [39]:
 temp = torch.tensor([
    [1, 2, 3], [4, 5, 6]
])
print('텐서의 크기')
print(temp.shape)
print('\n텐서를 4*1로 변경')
print(temp.view(6,1))
print('\n텐서를 1차원 벡터로 변경')
print(temp.view(-1))
print('\n텐서를 1*?로 변경')
print(temp.view(1, -1))
print('\n텐서를 ?*1로 변경')
print(temp.view(-1, 1))
print('\n텐서를 2*?로 변경')
print(temp.view(2, -1))
print('\n텐서를 ?*2로 변경')
print(temp.view(-1, 2))

텐서의 크기
torch.Size([2, 3])

텐서를 4*1로 변경
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

텐서를 1차원 벡터로 변경
tensor([1, 2, 3, 4, 5, 6])

텐서를 1*?로 변경
tensor([[1, 2, 3, 4, 5, 6]])

텐서를 ?*1로 변경
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


view를 이용해서 형태를 변형할 때, tensor의 원소 개수의 약수들을 활용해서 몇 개의 새로운 형태를 만들 수 있을지 계산하면 재밌겠다.  

상상한 코드  
tensor 원소 개수 세기 > 근데 기존 함수가 있지 않을까?  
tmp = []  
for(temp의 차원 수까지):  
  tmp.append(temp.shape[i])  
    if i > 2:  
      anw = tmp[i]*tmp[i-1]
  

## 2.2.2 데이터 준비
- 이미지: 분산된 파일에서 데이터 읽은 후, 전처리, 배치 단위로 분할하여 처리
- 텍스트: 임베딩 과정 후 서로 다른 길이의 시퀀스를 배치 단위로 분할하여 처리

### 단순하게 파일을 불러와서 사용
판다스 라이브러리를 이용해 JSON, PDF, CSV를 불러온다

### 커스텀 데이터셋을 만들어서 사용
커스텀 데이터셋: 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식

# !230613 여기서부터 다시 시작!
https://wikidocs.net/57165: 커스텀 데이터셋 자료  
https://wikidocs.net/16071: 클래스 설명 자료

In [47]:
import pandas as pd

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [56]:
cd /content/drive/MyDrive/projcet101/project101/Pytorch_tutorial

/content/drive/MyDrive/projcet101/project101/Pytorch_tutorial


In [57]:
pwd

'/content/drive/MyDrive/projcet101/project101/Pytorch_tutorial'

In [59]:
data = pd.read_csv('data/car_evaluation.csv')

In [62]:
data.head()

price  maint doors persons lug_capacity safety output
0  vhigh  vhigh     2       2        small    low  unacc
1  vhigh  vhigh     2       2        small    med  unacc
2  vhigh  vhigh     2       2        small   high  unacc
3  vhigh  vhigh     2       2          med    low  unacc
4  vhigh  vhigh     2       2          med    med  unacc

In [ ]:
x = torch.from_numpy((data['doors'].values)).unsqueeze(dim=1).float()