[참고 도서: 딥러닝 파이토치 교과서](https://www.yes24.com/Product/Goods/107664335)

# 2.1 파이토치 개요
## 2.1.1 파이토치 특징 및 장점

In [1]:
import torch

In [2]:
torch.tensor([[1, -1], [1, -1]])

tensor([[ 1, -1],
        [ 1, -1]])

# 2.2 파이토치 기초 문법
## 2.2.1 텐서 다루기

텐서는 넘파이의 ndarray와 비슷하고 GPU에서 연산도 가능하다

In [3]:
# 텐서 생성, GPU에 텐서 생성, dtype 이용해 텐서 생성
# colab에서 GPU를 사용할 경우, 별도로 노트 설정 옵션을 조정해야 함
print(torch.tensor([[1, 2], [3, 4]]))
# print(torch.tensor([[1, 2], [3, 4]], device = "cuda:0"))
print(torch.tensor([[1, 2], [3, 4]], dtype = torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


인덱스를 바로 지정하거나 슬라이스를 사용할 수 있다

In [4]:
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy())

[[1 2]
 [3 4]]


In [5]:
temp = torch.tensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print(temp[2:5], temp[4:-1])

tensor(1) tensor(2) tensor(7)
tensor([3, 4, 5]) tensor([5, 6])


텐서 간 타입이 다르면 연산이 불가능하다.  
- torch.FloatTensor: 32비트의 부동 소수점
- torch.DoubleTensor: 64비트의 부동 소수점
- torch.LongTensor: 4비트의 부호가 있는 정수

차원을 변경하는 방법: view, reshape과 유사함  
텐서를 결합하는 방법: stack, cat  
차원을 교환하는 방법: t, transpose

In [6]:
temp = torch.tensor([
    [1, 2], [3, 4]
])
print('텐서의 크기')
print(temp.shape)
print('\n텐서를 4*1로 변경')
print(temp.view(4,1))
print('\n텐서를 1차원 벡터로 변경')
print(temp.view(-1))
print('\n텐서를 1*?로 변경')
print(temp.view(1, -1))
print('\n텐서를 ?*1로 변경')
print(temp.view(-1, 1))
print('\n텐서를 4*?로 변경')
print(temp.view(4, -1))
print('\n텐서를 ?*4로 변경')
print(temp.view(-1, 4))

텐서의 크기
torch.Size([2, 2])

텐서를 4*1로 변경
tensor([[1],
        [2],
        [3],
        [4]])

텐서를 1차원 벡터로 변경
tensor([1, 2, 3, 4])

텐서를 1*?로 변경
tensor([[1, 2, 3, 4]])

텐서를 ?*1로 변경
tensor([[1],
        [2],
        [3],
        [4]])

텐서를 4*?로 변경
tensor([[1],
        [2],
        [3],
        [4]])

텐서를 ?*4로 변경
tensor([[1, 2, 3, 4]])


In [7]:
 temp = torch.tensor([
    [1, 2, 3], [4, 5, 6]
])
print('텐서의 크기')
print(temp.shape)
print('\n텐서를 4*1로 변경')
print(temp.view(6,1))
print('\n텐서를 1차원 벡터로 변경')
print(temp.view(-1))
print('\n텐서를 1*?로 변경')
print(temp.view(1, -1))
print('\n텐서를 ?*1로 변경')
print(temp.view(-1, 1))
print('\n텐서를 2*?로 변경')
print(temp.view(2, -1))
print('\n텐서를 ?*2로 변경')
print(temp.view(-1, 2))

텐서의 크기
torch.Size([2, 3])

텐서를 4*1로 변경
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

텐서를 1차원 벡터로 변경
tensor([1, 2, 3, 4, 5, 6])

텐서를 1*?로 변경
tensor([[1, 2, 3, 4, 5, 6]])

텐서를 ?*1로 변경
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

텐서를 2*?로 변경
tensor([[1, 2, 3],
        [4, 5, 6]])

텐서를 ?*2로 변경
tensor([[1, 2],
        [3, 4],
        [5, 6]])


view를 이용해서 형태를 변형할 때, tensor의 원소 개수의 약수들을 활용해서 몇 개의 새로운 형태를 만들 수 있을지 계산하면 재밌겠다.  

상상한 코드  
tensor 원소 개수 세기 > 근데 기존 함수가 있지 않을까?  
tmp = []  
for(temp의 차원 수까지):  
  tmp.append(temp.shape[i])  
    if i > 2:  
      anw = tmp[i]*tmp[i-1]
  

## 2.2.2 데이터 준비
- 이미지: 분산된 파일에서 데이터 읽은 후, 전처리, 배치 단위로 분할하여 처리
- 텍스트: 임베딩 과정 후 서로 다른 길이의 시퀀스를 배치 단위로 분할하여 처리

### 단순하게 파일을 불러와서 사용
판다스 라이브러리를 이용해 JSON, PDF, CSV를 불러온다

In [ ]:
import pandas as pd

In [62]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [64]:
cd /content/drive/MyDrive/projcet101/project101/Pytorch_tutorial

/content/drive/MyDrive/projcet101/project101/Pytorch_tutorial


In [65]:
pwd

'/content/drive/MyDrive/projcet101/project101/Pytorch_tutorial'

In [59]:
data = pd.read_csv('data/car_evaluation.csv')

In [62]:
data.head()

price  maint doors persons lug_capacity safety output
0  vhigh  vhigh     2       2        small    low  unacc
1  vhigh  vhigh     2       2        small    med  unacc
2  vhigh  vhigh     2       2        small   high  unacc
3  vhigh  vhigh     2       2          med    low  unacc
4  vhigh  vhigh     2       2          med    med  unacc

In [ ]:
# 구현안되는 부분
# x = torch.from_numpy((data['doors'].values)).unsqueeze(dim=1).float()

### 커스텀 데이터셋을 만들어서 사용
커스텀 데이터셋: 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식

In [60]:
import pandas as pd
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [61]:
class CustomDataset(Dataset):
  def __init__(self, csv_file):
    self.label = pd.read_csv(csv_file)
  def __len__(self):
    return len(self.label)
  def __getitem__(self, idx):
    sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
    label = torch.tensor(self.label.iloc[idx, 3]).int()
    return sample, label

In [69]:
tensor_dataset = CustomDataset('data/car_evaluation.csv')

In [70]:
dataset = DataLoader(tensor_dataset, batch_size = 4, shuffle = True)

In [ ]:
# 구현 안되는 부분

# for i, data in enumerate(dataset, 0):
#   print(i, end = ', ')
#   batch = data[0]
#   print(batch.size())

### 파이토치에서 제공하는 데이터셋 사용

In [74]:
import torchvision.transforms as transforms

In [76]:
mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])

In [78]:
from torchvision.datasets import MNIST
import requests
download_root = 'data'

In [81]:
train_dataset = MNIST(download_root, transform = mnist_transform, train = True, download = True)
valid_dataset = MNIST(download_root, transform = mnist_transform, train = False, download = True)
test_dataset = MNIST(download_root, transform = mnist_transform, train = False, download = True)

100%|██████████| 9912422/9912422 [00:00<00:00, 103677492.44it/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 9035931.21it/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 37914408.34it/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 5936593.57it/s]


Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



## 2.2.3 모델 정의
- 계층: 모듈 또는 모듈을 구성하는 한 개의 계층
- 모듈: 한 개 이상의 계층이 모여서 구성된 것
- 모델: 최종적으로 원하는 네트워크

### 단순 신경망을 정의하는 방법

In [83]:
from torch import nn

In [84]:
model = nn.Linear(in_features = 1, out_features = 1, bias = True)

In [85]:
model

Linear(in_features=1, out_features=1, bias=True)

### nn.Module()을 상속하여 정의하는 방법

In [88]:
class MLP(nn.Module):
  def __init__(self, inputs):
    super(MLP, self)._init__()
    self.layer = Linear(inputs, 1)
    self.activation = Sigmoid()
  
  def forward(self, X):
    X = self.layer(X)
    X = self.activation(X)
    return X

### Sequential 신경망을 정의하는 방법
nn.Sequential을 사용하면, \_\_init\_\_()함수에서 사용할 네트워크 모델을 정의해주고, forward()함수에서 모델에서 실행되어야할 계산을 좀 더 가독성 뛰어나게 코드로 작성할 수 있다.  
그 안에 포함된 각 모듈을 순차적으로 실행해주고, 모델의 계층이 복잡할 수록 효과가 뛰어나다

In [93]:
import torch.nn as nn

class MLP(nn.Module):
  def _init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = 5),
        nn.ReLU(inplace = True),
        nn.MaxPool2d(2)
    )
    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels = 64, out_channels = 30, kernel_size = 5),
        nn.ReLU(inplace = True),
        nn.MaxPool2d(2)
    )
    self.layer3 == nn.Seuential(
        nn.Linear(in_features = 30*5*5, out_features = 10, bias = True),
        nn.ReLU(inplace = True)
    )

    def forward(self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x.shape[0], -1)
      x = self.layer3[x]
      return x

model = MLP()

print("Printing childern\n---------------------------")
print(list(model.children()))
print("\nPrinting childern\n---------------------------")
print(list(model.modules()))


Printing childern
---------------------------
[]

Printing childern
---------------------------
[MLP()]


### 함수로 신경망을 정의하는 방법
변수에 저장해 놓은 계층들을 재사용할 수 있는 장점과 모델이 복잡해진다는 단점이 있다.

In [94]:
def MLP(in_features = 1, hidden_features = 20, out_features = 1):
  hidden = nn.Linear(in_features = in_features, out_fetures = hidden_features, bias = True)
  activation = nn.ReLU()
  output = nn.Linear(in_features = hidden_features, out_features = out_features, bias = True)
  net = nn.Sequential(hidden, activation, output)

  return net

## 2.2.4 모델의 파라미터 정의